version: "3"

volumes:
  redis-data:
  php-var:

services:
  application:
    container_name: application
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: dev
    volumes:
    #- "${PWD}:/application/"
    - "php-var:/application/var"
    ports:
      - "4000:80"
    depends_on:
      - redis-cache
  redis-cache:
    container_name: redis-cache
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - "redis-data:/data"
    restart: always

